CC = g++
CFLAGS = -Wall -std=c++17

all: mycat mygrep

mycat: mycat.cpp
	$(CC) $(CFLAGS) -o mycat mycat.cpp

mygrep: mygrep.cpp
	$(CC) $(CFLAGS) -o mygrep mygrep.cpp

clean:
	rm -f mycat mygrep
